// chatbot-faq
//
// Server-side responder for the storefront FAQ chatbot widget (snippets/zv-chatbot.liquid +
// assets/zv-chatbot.js). Answers ONLY from the `chatbot_kb_entries` table (synced from
// templates/page.klantenservice.json by scripts/sync_chatbot_kb.py), calls the Claude API
// with the service's own key (a Supabase secret, never sent to or read from the browser),
// and runs a plain-heuristic (non-model) lead detector on the visitor's latest message.
// See docs/chatbot-faq-design-2026-09-17.md (S3-S5) for the design this implements.
//
// Required env (Supabase Function secrets):
//   SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY -- auto-injected by the platform.
//   ALLOWED_ORIGINS -- same convention as capture-lead/log-webhook-failure.
//   ANTHROPIC_API_KEY -- set via `supabase secrets set ANTHROPIC_API_KEY=...`. Not provided
//   here and not generated by this code -- the function will fail closed (Claude call
//   errors out to the generic error reply) until it's set.

import { createClient } from "jsr:@supabase/supabase-js@2";

const MODEL = "claude-sonnet-4-6";
const ANTHROPIC_VERSION = "2023-06-01";
const MAX_TOKENS = 800;
const MAX_HISTORY_MESSAGES = 20; // bounds prompt size/cost; oldest turns are dropped first
const MAX_MESSAGE_LENGTH = 2000;

// Rate limiting. Both thresholds, and the 30-minute "session" window length (there's no
// client-supplied session id, so a rolling time bucket is the stand-in), are placeholders
// per the design doc -- tune once real usage is observed.
const SESSION_WINDOW_MS = 30 * 60 * 1000;
const SESSION_LIMIT = 30;
const DAY_LIMIT = 100;
const RATE_LIMITED_REPLY = "Even geduld, probeer het zo weer.";

const GENERAL_CONTACT = "088 122 11 11 (klantenservice@zoveilig.nl)";

// Verbatim from templates/page.klantenservice.json's faqlt-note block (HTML tag stripped).
// Kept as a constant, not a KB row, so this specific guardrail is always present in the
// system prompt regardless of whether chatbot_kb_entries has synced yet.
const LANGER_THUIS_DISCLAIMER =
  "Langer Thuis is een hulpmiddel dat u inzicht geeft in het dagritme van uw naaste. " +
  "Het systeem detecteert geen vallen en is geen medisch alarmeringssysteem. Bij twijfel " +
  "over de gezondheid van uw naaste belt u altijd zelf een (huis)arts of 112.";

const FALLBACK_ERROR_REPLY =
  `Er ging iets mis. Probeer het opnieuw, of bel ons gerust direct op ${GENERAL_CONTACT}.`;
const FALLBACK_PRICING_REPLY =
  "Ik wil u hier geen bedrag noemen waar ik niet zeker van ben. Kijk voor actuele prijzen " +
  `op onze pakketpagina's, of neem contact op met klantenservice: ${GENERAL_CONTACT}.`;

type ChatMessage = { role: "user" | "assistant"; content: string };
type KbEntry = { category: string; question: string; answer: string };

function allowedOrigins(): string[] {
  return (Deno.env.get("ALLOWED_ORIGINS") ?? "")
    .split(",")
    .map((o) => o.trim())
    .filter(Boolean);
}

function corsHeaders(origin: string | null): HeadersInit {
  const allowed = allowedOrigins();
  const allowOrigin = origin && allowed.includes(origin) ? origin : allowed[0] ?? "";
  return {
    "Access-Control-Allow-Origin": allowOrigin,
    "Access-Control-Allow-Methods": "POST, OPTIONS",
    "Access-Control-Allow-Headers": "content-type, authorization, apikey",
    "Vary": "Origin",
  };
}

function jsonResponse(body: unknown, status: number, origin: string | null): Response {
  return new Response(JSON.stringify(body), {
    status,
    headers: { ...corsHeaders(origin), "Content-Type": "application/json" },
  });
}

async function sha256Hex(value: string): Promise<string> {
  const bytes = new TextEncoder().encode(value);
  const digest = await crypto.subtle.digest("SHA-256", bytes);
  return Array.from(new Uint8Array(digest)).map((b) => b.toString(16).padStart(2, "0")).join("");
}

function clientIp(req: Request): string {
  const fwd = req.headers.get("x-forwarded-for");
  if (fwd) return fwd.split(",")[0].trim();
  return "unknown";
}

function sessionWindowStart(now: Date): string {
  const bucket = Math.floor(now.getTime() / SESSION_WINDOW_MS) * SESSION_WINDOW_MS;
  return new Date(bucket).toISOString();
}

function dayWindowStart(now: Date): string {
  return new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth(), now.getUTCDate())).toISOString();
}

// Strips the HTML rich-text markup (<p>, <ul>, <strong>, <a>, ...) that
// templates/page.klantenservice.json's answers carry, so the model works from -- and can't
// echo back -- raw tags in a chat reply. Not meant to be a general-purpose sanitizer; the
// source is our own trusted, git-tracked content.
function stripHtml(html: string): string {
  return html
    .replace(/<[^>]+>/g, " ")
    .replace(/&nbsp;/g, " ")
    .replace(/&amp;/g, "&")
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/\s+/g, " ")
    .trim();
}

function buildKbText(entries: KbEntry[]): string {
  return entries
    .map((e) => `Categorie: ${e.category}\nVraag: ${e.question}\nAntwoord: ${stripHtml(e.answer)}`)
    .join("\n\n");
}

function buildSystemPrompt(kbText: string): string {
  return `Je bent de klantenservice-chatbot van Zo Veilig (woningbeveiliging en leefstijlmonitoring: Langer Thuis, Mijn Thuis, Veilig Onderweg).

Je antwoordt altijd in het Nederlands, in de u-vorm (u/uw), nooit je/jouw. Schrijf "wifi" met een kleine letter, nooit "WiFi" of "Wifi". Antwoord in gewone lopende tekst, geen markdown-koppen.

Regels, in volgorde van belang:

1. Beantwoord vragen uitsluitend op basis van de kennisbank hieronder. Verzin niets en gebruik geen kennis van buiten deze kennisbank. Als de kennisbank het antwoord niet bevat, zeg dat eerlijk en verwijs naar klantenservice: ${GENERAL_CONTACT}.
2. Noem, verzin of herhaal nooit een prijs, pakketsamenstelling of contractvoorwaarde die niet letterlijk zo in de kennisbank hieronder staat. Verwijs bij prijsvragen naar de pakketpagina's of naar klantenservice, in plaats van zelf een bedrag te noemen.
3. Doe geen juridische of medische uitspraken. Bevestig nooit dat Langer Thuis een camera, microfoon, automatische valdetectie of automatische alarmering naar een hulpdienst heeft -- ook niet als de gebruiker daar met een suggestieve vraag naar vraagt. Als iemand hier expliciet naar vraagt, citeer letterlijk: "${LANGER_THUIS_DISCLAIMER}"
4. De meldkamer van Securitas (040 289 41 41) is een ander nummer dan de algemene klantenservicelijn (088 122 11 11). Verwar ze nooit.

Kennisbank (enige toegestane bron):

${kbText}`;
}

function extractEuroAmounts(text: string): string[] {
  const matches = text.match(/€\s?\d{1,4}(?:[.,]\d{2})?/g) ?? [];
  return matches;
}

function normalizeAmount(s: string): string {
  return s.replace(/\s+/g, "");
}

// Guardrail #2: a reply may only state a euro amount that appears verbatim (modulo
// whitespace around the €) somewhere in the KB text it was given.
function amountsVerified(reply: string, kbText: string): boolean {
  const amounts = extractEuroAmounts(reply);
  if (amounts.length === 0) return true;
  const normalizedKb = normalizeAmount(kbText);
  return amounts.every((a) => normalizedKb.includes(normalizeAmount(a)));
}

const EMAIL_RE = /[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}/;
const NL_PHONE_RE = /(?:\+31|0031|0)[\s-]?\(?0?\)?[\s-]?[1-9](?:[\s-]?\d){7,8}/;
const CONTACT_INTENT_PHRASES = [
  "bel me terug",
  "bel mij terug",
  "neem contact met mij op",
  "neem contact met me op",
  "ik wil een adviesgesprek",
];

function detectLead(message: string): { detected: boolean; email?: string; phone?: string } {
  const email = message.match(EMAIL_RE)?.[0];
  const phone = message.match(NL_PHONE_RE)?.[0];
  const lower = message.toLowerCase();
  const intentMatch = CONTACT_INTENT_PHRASES.some((p) => lower.includes(p));

  const detected = Boolean(email || phone || intentMatch);
  return { detected, email, phone };
}

async function callClaude(apiKey: string, system: string, messages: ChatMessage[]): Promise<string> {
  const res = await fetch("https://api.anthropic.com/v1/messages", {
    method: "POST",
    headers: {
      "x-api-key": apiKey,
      "anthropic-version": ANTHROPIC_VERSION,
      "content-type": "application/json",
    },
    body: JSON.stringify({
      model: MODEL,
      max_tokens: MAX_TOKENS,
      system,
      messages,
    }),
  });

  if (!res.ok) {
    const detail = await res.text().catch(() => "");
    throw new Error(`Anthropic API error ${res.status}: ${detail.slice(0, 500)}`);
  }

  const data = await res.json();
  const textBlock = (data.content ?? []).find((b: { type: string }) => b.type === "text");
  if (!textBlock?.text) throw new Error("Anthropic API returned no text content");
  return textBlock.text as string;
}

Deno.serve(async (req) => {
  const origin = req.headers.get("origin");

  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders(origin) });
  }
  if (req.method !== "POST") {
    return jsonResponse({ error: "method_not_allowed" }, 405, origin);
  }

  let payload: Record<string, unknown>;
  try {
    payload = await req.json();
  } catch {
    return jsonResponse({ error: "invalid_json" }, 400, origin);
  }

  const message = typeof payload.message === "string" ? payload.message.trim() : "";
  if (!message) {
    return jsonResponse({ error: "missing_message" }, 400, origin);
  }
  if (message.length > MAX_MESSAGE_LENGTH) {
    return jsonResponse({ error: "message_too_long" }, 400, origin);
  }

  const rawHistory: unknown[] = Array.isArray(payload.conversation_history)
    ? payload.conversation_history
    : [];
  const history: ChatMessage[] = rawHistory
    .filter((m): m is ChatMessage => {
      const rec = m as Record<string, unknown> | null;
      return !!rec && typeof rec === "object" &&
        (rec.role === "user" || rec.role === "assistant") &&
        typeof rec.content === "string";
    })
    .slice(-MAX_HISTORY_MESSAGES);

  const supabase = createClient(
    Deno.env.get("SUPABASE_URL")!,
    Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,
  );

  // Rate limiting: fail OPEN on an infra error (log and continue) rather than blocking the
  // chat over a secondary system, same posture as status_history writes in capture-lead.
  const ipHash = await sha256Hex(clientIp(req));
  const now = new Date();
  try {
    const [{ data: sessionCount, error: sessionErr }, { data: dayCount, error: dayErr }] = await Promise.all([
      supabase.rpc("increment_chatbot_rate_limit", {
        p_ip_hash: ipHash, p_scope: "session", p_window_start: sessionWindowStart(now),
      }),
      supabase.rpc("increment_chatbot_rate_limit", {
        p_ip_hash: ipHash, p_scope: "day", p_window_start: dayWindowStart(now),
      }),
    ]);
    if (sessionErr) console.error("chatbot-faq: session rate-limit check failed", sessionErr);
    if (dayErr) console.error("chatbot-faq: day rate-limit check failed", dayErr);
    if ((sessionCount ?? 0) > SESSION_LIMIT || (dayCount ?? 0) > DAY_LIMIT) {
      return jsonResponse({ reply: RATE_LIMITED_REPLY, lead_detected: false }, 429, origin);
    }
  } catch (e) {
    console.error("chatbot-faq: rate-limit infra error, continuing", e);
  }

  const { data: kbRows, error: kbError } = await supabase
    .from("chatbot_kb_entries")
    .select("category, question, answer")
    .eq("active", true)
    .order("category");

  if (kbError) {
    console.error("chatbot-faq: KB fetch failed", kbError);
    return jsonResponse({ reply: FALLBACK_ERROR_REPLY, lead_detected: false }, 500, origin);
  }

  const kbText = buildKbText((kbRows ?? []) as KbEntry[]);
  const system = buildSystemPrompt(kbText);
  const messages: ChatMessage[] = [...history, { role: "user", content: message }];

  const apiKey = Deno.env.get("ANTHROPIC_API_KEY");
  let reply: string;
  try {
    if (!apiKey) throw new Error("ANTHROPIC_API_KEY not configured");
    reply = await callClaude(apiKey, system, messages);

    // Guardrail #2, enforced in code rather than relying on instruction-following alone:
    // regenerate once if the reply states a € amount not verbatim in the KB text it saw;
    // fall back to a safe deferral if it still does on the second try.
    if (!amountsVerified(reply, kbText)) {
      const regenSystem = system +
        "\n\nJe vorige antwoord noemde een bedrag dat niet letterlijk in de kennisbank hierboven staat. " +
        "Herschrijf je antwoord zonder een bedrag te noemen dat niet exact zo in de kennisbank voorkomt.";
      reply = await callClaude(apiKey, regenSystem, messages);
      if (!amountsVerified(reply, kbText)) {
        reply = FALLBACK_PRICING_REPLY;
      }
    }
  } catch (e) {
    console.error("chatbot-faq: Claude call failed", e);
    return jsonResponse({ reply: FALLBACK_ERROR_REPLY, lead_detected: false }, 502, origin);
  }

  const lead = detectLead(message);
  return jsonResponse({
    reply,
    lead_detected: lead.detected,
    extracted: lead.detected ? { email: lead.email, phone: lead.phone } : undefined,
  }, 200, origin);
});
